### PR TITLE
Rename docker types to container

### PR DESCRIPTION
**Pull request by rhatdan**
Docker has asked for packages beginning with the name docker be removed from
github.  We want to follow their requests and since we plan on using this
policy for other container runtimes, we need to rename the types to something
more generic.

We will need to be careful when updating docker.pp based systems to container.pp.

### CODE REVIEW

**Comment by rhatdan** [comment]
@wrabcak @lsm5 PTAL.
I think we should rename the github from docker-selinux to container-selinux also.

**Comment by lsm5** [comment]
sgtm, i'll try scratch builds on rawhide with this PR

**Comment by rhatdan** [comment]
@lsm5 Look in container-selinux.spec for postinstall and postuninstall code.  I think you will need to do this for some of your code also.
Also need to make sure docker.if is not still installed after the install of container.pp

**Comment by lsm5** [comment]
On Mon, Oct 03, 2016 at 07:21:38AM -0700, Daniel J Walsh wrote:
> @lsm5 Look in container-selinux.spec for postinstall and postuninstall code.  I think you will need to do this for some of your code also.
> Also need to make sure docker.if is not still installed after the install of container.pp
> 

Yup, I'm changing those as and when rpmbuild points out.

-- 
Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
On Mon, Oct 03, 2016 at 07:21:38AM -0700, Daniel J Walsh wrote:
> @lsm5 Look in container-selinux.spec for postinstall and postuninstall code.  I think you will need to do this for some of your code also.
> Also need to make sure docker.if is not still installed after the install of container.pp

@rhatdan, we'll also need to edit Makefile to have `TARGETS?=container` 

-- 
Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by rhatdan** [comment]
Fixed

**Comment by lsm5** [comment]
On Mon, Oct 03, 2016 at 07:53:11AM -0700, Daniel J Walsh wrote:
> Fixed

seems to work fine on my machine. PTAL @ scratch build
http://koji.fedoraproject.org/koji/taskinfo?taskID=15925350 whenever it
completes.

-- 
Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
@rhatdan scratch build LGTY?

**Comment by rhatdan** [comment]
I think you are missing obsoletes docker-selinux.  We want to make sure docker-selinux does not get installed.

**Comment by lsm5** [comment]
On Mon, Oct 03, 2016 at 09:40:32AM -0700, Daniel J Walsh wrote:
> I think you are missing obsoletes docker-selinux.  We want to make sure docker-selinux does not get installed.
> 

I have this in my spec right now:

    %package -n container-selinux
    URL: %{git2} 
    Summary: SELinux policies for Docker
    BuildRequires: selinux-policy
    BuildRequires: selinux-policy-devel
    Requires(post): selinux-policy-base >= %{selinux_policyver}
    Requires(post): policycoreutils
    %if 0%{?fedora}
    Requires(post): policycoreutils-python-utils
    %else
    Requires(post): policycoreutils-python
    %endif
    Requires(post): libselinux-utils
    Provides: %{repo}-io-selinux = %{epoch}:%{version}-%{release}
    Obsoletes: %{repo}-selinux <= %{epoch}:%{version}-28
    Provides: %{repo}-selinux = %{epoch}:%{version}-%{release}


What error do you see on installation?

-- 
Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
I see I gotta change the Summary line in there

**Comment by rhatdan** [comment]
Isn't repo now container instead of docker?

 Obsoletes: docker-selinux <= %{epoch}:%{version}-28 
Provides: docker-selinux = %{epoch}:%{version}-%{release}

**Comment by lsm5** [comment]
%{repo} is the name of the main upstream package repo, which is 'docker'. See: https://pkgs.fedoraproject.org/cgit/rpms/docker.git/tree/docker.spec#n25

And the subpackage is now `container-selinux`: 
`%package -n container-selinux` which will Obsoletes: docker-selinux previous build and Provides: docker-selinux.

Does that answer your question?

**Comment by lsm5** [comment]
the %package -n container-selinux change hasn't been pushed to dist-git yet btw

**Comment by rhatdan** [comment]
I was able to reinstall docker-selinux after installing  container-selinux, which is what I did not expect.  I would like to see this package prevented by being installed.

**Comment by rhatdan** [comment]
Perhaps we want 
rpm -q container-selinux --obsoletes
docker-selinux

Not 
rpm -q container-selinux --obsoletes
docker-selinux <= 2:1.12.1-28

**Comment by lsm5** [comment]
that's probably happening cause the latest build with container-selinux isn't in rawhide repos yet. See https://pkgs.fedoraproject.org/cgit/rpms/docker.git/tree/docker.spec#n171 for the case where docker obsoleted docker-io.

But anyway, that change isn't a blocker to this PR, I'll change and verify on the rpm side for docker|container-selinux conflicts. Could you merge this PR please?

**Comment by lsm5** [comment]
thanks @rhatdan

**Comment by lsm5** [comment]
also, do you wanna move the repo to container-selinux while we're at it?

**Pull request merged**
